# WIP

# uses node js license-checker to generate the list of deps of this project in the format used by brooklyn
# there is more to do to write the metadata for each of these deps

license-checker --production | sed 's/^.─ \(.*\)/\1:/' | sed 's/^.  ├─ /  /' | sed 's/^.  └─ /  /' | sed 's/.  .  .─/    /' | sed 's/\( *licenses\)$/\1:/' | sed 's/\(url: \)\(@.*\)$/\1"\2"/' | sed 's/\(.*: .*\):\( .*\)/\1-\2/' | sed 's/^\([^ ].*\):$/- id: \1/' > config/license-dependencies.1.tmp

grep -- "^- id:" config/license-dependencies.1.tmp | grep -v "id: brooklyn-" > config/license-inclusions-source-autogenerated-js-license-checker.yaml

