i#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# WIP

# uses node js license-checker to generate the list of deps of this project in the format used by brooklyn
# there is more to do to write the metadata for each of these deps

license-checker --production | sed 's/^.─ \(.*\)/\1:/' | sed 's/^.  ├─ /  /' | sed 's/^.  └─ /  /' | sed 's/.  .  .─/    /' | sed 's/\( *licenses\)$/\1:/' | sed 's/\(url: \)\(@.*\)$/\1"\2"/' | sed 's/\(.*: .*\):\( .*\)/\1-\2/' | sed 's/^\([^ ].*\):$/- id: \1/' > config/license-dependencies.1.tmp

grep -- "^- id:" config/license-dependencies.1.tmp | grep -v "id: brooklyn-" > config/license-inclusions-source-autogenerated-js-license-checker.yaml

